"""DriverEvent association table

Revision ID: 6f726a612d82
Revises: 41748cbb43bb
Create Date: 2025-01-26 20:59:23.258408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f726a612d82'
down_revision = '41748cbb43bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laptime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_event_id', sa.Integer(), nullable=False),
    sa.Column('laptime', sa.Interval(), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_event_id'], ['driver_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('laptime', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_laptime_run_number'), ['run_number'], unique=False)

    op.drop_table('_alembic_tmp_driver')
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.drop_index('ix_driver_driver_car')
        batch_op.drop_column('driver_car')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_date', sa.Date(), nullable=False))
        batch_op.create_index(batch_op.f('ix_event_event_date'), ['event_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_event_date'))
        batch_op.drop_column('event_date')

    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_car', sa.VARCHAR(length=64), nullable=False))
        batch_op.create_index('ix_driver_driver_car', ['driver_car'], unique=1)

    op.create_table('_alembic_tmp_driver',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('driver_name', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('laptime', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_laptime_run_number'))

    op.drop_table('laptime')
    # ### end Alembic commands ###
