"""unique driver event constraint

Revision ID: 79164d50c062
Revises: 2fea2975f47f
Create Date: 2025-01-31 22:44:10.053320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79164d50c062'
down_revision = '2fea2975f47f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_event', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_driver_event', ['driver_id', 'event_id', 'car_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_event', schema=None) as batch_op:
        batch_op.drop_constraint('unique_driver_event', type_='unique')

    # ### end Alembic commands ###
