"""Event table

Revision ID: 989d3df3ee86
Revises: 41748cbb43bb
Create Date: 2025-01-23 20:36:25.786704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989d3df3ee86'
down_revision = '41748cbb43bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_date', sa.Date(), nullable=False))
        batch_op.create_index(batch_op.f('ix_event_event_date'), ['event_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_event_date'))
        batch_op.drop_column('event_date')

    # ### end Alembic commands ###
