"""update

Revision ID: ad592a4f8c09
Revises: c86ea21a3c3d
Create Date: 2025-04-20 16:50:55.179932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad592a4f8c09'
down_revision = 'c86ea21a3c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_name', sa.String(length=64), nullable=False),
    sa.Column('car_class', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_name', 'car_class', name='unique_car')
    )
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_car_car_class'), ['car_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_car_name'), ['car_name'], unique=False)

    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_driver_name'), ['driver_name'], unique=True)

    op.create_table('event_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_type_event_type_name'), ['event_type_name'], unique=True)

    op.create_table('season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_name', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_season_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_season_season_name'), ['season_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_season_start_date'), ['start_date'], unique=False)

    op.create_table('driver_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('total_events', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver_season_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_season_stats_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_season_stats_season_id'), ['season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_season_stats_total_events'), ['total_events'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_season_stats_total_points'), ['total_points'], unique=False)

    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=64), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_type.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_event_name'), ['event_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_event_event_type_id'), ['event_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_season_id'), ['season_id'], unique=False)

    op.create_table('driver_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id', 'event_id', 'car_id', name='unique_driver_event')
    )
    with op.batch_alter_table('driver_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_event_car_id'), ['car_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_event_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_event_event_id'), ['event_id'], unique=False)

    op.create_table('driver_event_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_event_id', sa.Integer(), nullable=False),
    sa.Column('fastest_lap', sa.Interval(), nullable=True),
    sa.Column('average_lap', sa.Interval(), nullable=True),
    sa.Column('total_laps', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_event_id'], ['driver_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver_event_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_event_stats_driver_event_id'), ['driver_event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_driver_event_stats_total_laps'), ['total_laps'], unique=False)

    op.create_table('laptime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_event_id', sa.Integer(), nullable=False),
    sa.Column('laptime', sa.Interval(), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_event_id'], ['driver_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('laptime', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_laptime_run_number'), ['run_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptime', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_laptime_run_number'))

    op.drop_table('laptime')
    with op.batch_alter_table('driver_event_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_event_stats_total_laps'))
        batch_op.drop_index(batch_op.f('ix_driver_event_stats_driver_event_id'))

    op.drop_table('driver_event_stats')
    with op.batch_alter_table('driver_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_event_event_id'))
        batch_op.drop_index(batch_op.f('ix_driver_event_driver_id'))
        batch_op.drop_index(batch_op.f('ix_driver_event_car_id'))

    op.drop_table('driver_event')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_season_id'))
        batch_op.drop_index(batch_op.f('ix_event_event_type_id'))
        batch_op.drop_index(batch_op.f('ix_event_event_name'))
        batch_op.drop_index(batch_op.f('ix_event_event_date'))

    op.drop_table('event')
    with op.batch_alter_table('driver_season_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_season_stats_total_points'))
        batch_op.drop_index(batch_op.f('ix_driver_season_stats_total_events'))
        batch_op.drop_index(batch_op.f('ix_driver_season_stats_season_id'))
        batch_op.drop_index(batch_op.f('ix_driver_season_stats_driver_id'))

    op.drop_table('driver_season_stats')
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_season_start_date'))
        batch_op.drop_index(batch_op.f('ix_season_season_name'))
        batch_op.drop_index(batch_op.f('ix_season_end_date'))

    op.drop_table('season')
    with op.batch_alter_table('event_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_type_event_type_name'))

    op.drop_table('event_type')
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_driver_name'))

    op.drop_table('driver')
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_car_name'))
        batch_op.drop_index(batch_op.f('ix_car_car_class'))

    op.drop_table('car')
    # ### end Alembic commands ###
